[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name="KiKit"
version="1.0.1"
dynamic = ["dependencies"]
authors=[
    {name="Jan Mrázek", email="email@honzamrazek.cz"}]
requires-python='>=3.7'
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
description="Automation for KiCAD boards"
keywords=['kikit', 'kicad', 'python', 'eda', 'electronics', 'pcb', 'manufacturing']
readme="README.md"

[project.license]
file="LICENSE"
test="MIT"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.hatch.metadata]
allow-direct-references = true

[project.scripts]
kikit="kikit.ui:cli"
kikit-info="kikit.info:cli"

[project.urls]
github="https://github.com/yaqwsx/KiKit"

[tool.setuptools.packages.find]
where = ["src"]
