name: Bug report
description: Create a report to help us improve
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: I have read [FAQ](https://yaqwsx.github.io/KiKit/latest/faq/)
      required: true
    - label: I have searched existing issues (including closed ones)
      required: true
    - label: I use KiKit at least version 1.6.0 (older version are not supported)
      required: true
- type: input
  attributes:
    label: KiKit version
    description: The output of `kikit --version`
  validations:
    required: true
- type: input
  attributes:
    label: KiCAD version
    description: available in KiCAD under Help -> About KiCAD
  validations:
    required: true
- type: input
  attributes:
    label: Operating system
    description: for Linux, please specify the distribution
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: >
      A description of the bug. If applicable please specify what behavior do
      you expect and what behavior did you observe.

      If you run into KiKit crashing, please rerun the command with `--debug
      'trace: true'` (when using the panelize command) or with `--debug` (when
      using any other command) and include the output in the error log. Please,
      enclose the log into a code block. Not including the log might
      significantly increase time for handling the issue.

      If applicable, add screenshots to explain your problem. Note that if file
      type is not supported by GitHub, you can put them in a ZIP archive.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: >
      Please specify the steps to reproduce the issue. Do not forget to include
      the KiKit command and also, please include any input boards you use. If
      the boards are confidential, you can send them to email@honzamrazek.cz
      with subject "KiKit issue files for #123".

      Issues without included PCB will be probably ignored. Having to came up
      with a specific inputs that reproduce the issue is a significant time
      overhead and I prefer to spend this time on implementing new features.
  validations:
    required: true
